
pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=geminihlswadmin
      - body~=labels:.*semver-patch.*
      - status-success=build
    actions:
      merge:
        method: merge
